#! /bin/sh
#
# Panel for lemonbar

. panel_colors

num_mon=$(bspc query -M | wc -l)

icon() {
    echo -e -n "%{T1}\u$1%{T-}"
}

battery() {
    prefix="$(icon f240)"
    batc=$(cat /sys/class/power_supply/BAT1/capacity)
    bats=$(cat /sys/class/power_supply/BAT1/status)
	
    if [ "$bats" = "Charging" ]; then
	    prefix="$(icon f1e6)"
    fi

    echo "$prefix" "$batc"
}

volume() {
    amixer get Master | awk '$0~/%/{print $4}' | tr -d '[]%'
}

power() {
	echo -n "%{A:systemctl poweroff:}%{A3:systemctl reboot:} $(icon f011) %{A}%{A}"
}

while read -r line ; do
	case $line in
		S*)
			# clock output
			clock="%{F$COLOR_CLOCK_FG}%{B$COLOR_CLOCK_BG} $(icon f017) ${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output
        		if [ ${#line} -ge 40 ]
		            	then
					xtitle=$(echo ${line#?} | cut -c1-40)...
				else
					xtitle=$(echo ${line#?})
		        fi

			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${xtitle} %{B-}%{F-}"
			;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FREE_BG
								;;
							F*)
								# focused free desktop
								FG=$COLOR_FOCUSED_FREE_FG
								BG=$COLOR_FOCUSED_FREE_BG
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								BG=$COLOR_OCCUPIED_BG
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED_FG
								BG=$COLOR_FOCUSED_OCCUPIED_BG
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_URGENT_BG
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_FOCUSED_URGENT_FG
								BG=$COLOR_FOCUSED_URGENT_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[LTG]*)
						# layout, state and flags
						wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name}%{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac

	battery="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} $(battery)% %{B-}%{F-}"
	volume="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} $(icon f028) $(volume)% %{B-}%{F-}"
	power="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} $(power) %{B-}%{F-}"

	bar=""
	i=0
	while (($i < $num_mon)); do
	    bar="${bar} %{S${i}} %{l}${wm}${title} %{c}${clock} %{r}${volume}${battery}${power}"
	    let i=$i+1
	done

	printf "%s\n" "${bar}"
done
