#! /bin/sh

# monitors
bspc monitor eDP1 -n A -d 1 2 3 4 5
bspc monitor HDMI2 -n B -d 6 7 8 9 10

# dimensions
bspc config border_width         3
bspc config window_gap           13
bspc config split_ratio          0.50

# monocle
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# focus
bspc config focus_follows_pointer true
bspc config focus_by_distance     true
bspc config click_to_focus 	  true

# colors
#bspc config normal_border_color ""
#bspc config active_border_color ""
bspc config focused_border_color "#b452ff"
#bspc config presel_feedback_color ""

# panel
panel &
